CREATE DATABASE IF NOT EXISTS db_feedbacks;

USE db_feedbacks;

-- TABELA USUÁRIOS

CREATE TABLE IF NOT EXISTS tb_users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    password VARCHAR(30) NOT NULL
);

-- TABELA COMENTÁRIOS

CREATE TABLE IF NOT EXISTS tb_comments (
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
    message TEXT NOT NULL,
    dt DATETIME DEFAULT NOW(),
    likes INT DEFAULT 0
);