CREATE DATABASE IF NOT EXISTS db_feedbacks;

USE db_feedbacks;

CREATE TABLE IF NOT EXISTS tb_comentarios (
	id INT PRIMARY KEY AUTO_INCREMENT,
	user VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    dt DATETIME DEFAULT NOW()
);